from enum import StrEnum


class DialogueState(StrEnum):
    NEW = "new"
    ASK_FULL_NAME = "ask_full_name"
    ASK_EXECUTOR_TYPE = "ask_executor_type"
    ASK_PHONE = "ask_phone"
    ASK_CITY = "ask_city"
    ASK_ADDRESS = "ask_address"
    ASK_IIN = "ask_iin"
    ASK_BIRTH_DATE = "ask_birth_date"
    ASK_DRIVING_EXPERIENCE_SINCE = "ask_driving_experience_since"
    ASK_HAS_CAR = "ask_has_car"
    ASK_EXISTING_VEHICLE_IDENTIFIER = "ask_existing_vehicle_identifier"
    ASK_CAR_BRAND = "ask_car_brand"
    ASK_CAR_MODEL = "ask_car_model"
    ASK_CAR_YEAR = "ask_car_year"
    ASK_CAR_PLATE = "ask_car_plate"
    ASK_CAR_COLOR = "ask_car_color"
    ASK_DRIVER_LICENSE_NUMBER = "ask_driver_license_number"
    ASK_DRIVER_LICENSE_ISSUE_DATE = "ask_driver_license_issue_date"
    ASK_DRIVER_LICENSE_EXPIRES_AT = "ask_driver_license_expires_at"
    ASK_EMPLOYMENT_TYPE = "ask_employment_type"
    ASK_HIRED_AT = "ask_hired_at"
    ASK_HEARING_IMPAIRED = "ask_hearing_impaired"
    ASK_DRIVER_LICENSE_FRONT = "ask_driver_license_front"
    ASK_DRIVER_LICENSE_BACK = "ask_driver_license_back"
    ASK_ID_CARD = "ask_id_card"
    ASK_VEHICLE_REGISTRATION_DOC = "ask_vehicle_registration_doc"
    ASK_SELFIE_WITH_LICENSE = "ask_selfie_with_license"
    ASK_RENT_OR_POWER_OF_ATTORNEY = "ask_rent_or_power_of_attorney"
    CONFIRM_DATA = "confirm_data"
    READY_TO_SEND_YANDEX = "ready_to_send_yandex"
    SENDING_TO_YANDEX = "sending_to_yandex"
    SENT_TO_YANDEX = "sent_to_yandex"
    YANDEX_ERROR = "yandex_error"
    DUPLICATE_REJECTED = "duplicate_rejected"
    COMPLETED = "completed"
